# This is a basic workflow that is manually triggered

name: Deploy to the prod server

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Execute SSH commmands on remote server
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: '${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST_PROD }}'
        privateKey: ${{ secrets.DEPLOY_KEY }}
        debug: true
        command: |
          cd /opt/attr_lingvo
          sudo git pull
          sudo yarn build
          sudo systemctl restart attr_lingvo

